### PR TITLE
Add Dockerfile for containerizing specified prebuilt release.

### PR DESCRIPTION
**Pull request by Cam2337**
- Created Dockerimage file layering ontop of the [python:3.7.5-buster image](https://github.com/docker-library/python/blob/0b1fb9529c79ea85b8c80ff3dd85a32a935b0346/3.7/buster/Dockerfile)

- Uploaded this `snap-python` Docker image to Docker Hub for public use/downloading: (https://hub.docker.com/repository/docker/cam2337/snap-python)
    - **Note:** Is there an official Stanford account we could use for this?

- Created a detailed README.md specifying:
    - OS requirements for Docker
    - Docker installation procedure for macOS/Windows/Linux
    - How to build the snap-python image (either locally or pulling it from Docker Hub)
    - How to create an interactive Python session within the container to import snap
    - How to specify/mount a working directory to execute a snap-based Python application
    - How to create a custom Docker image to specify additional Python requirements (outside of the requirements we provide in the snap-python image)
    - How to create a custom build-system in your favorite text editor (with Sublime Text example) so that you can build against this snap-python compute stack right from an editor

### CODE REVIEW

**Comment by benhannel** [comment]
This is super cool! I think the formatting on your README is a little bit off (see step 6 and on), and it would be good to add installation instructions for Mac and Windows. I believe those are the most common platforms for students. Or even better, just write a bash script that does the whole installation (with some comments)

**Comment by benhannel** [comment]
Mac install and run worked like a charm! Really nice work. Would you clean up the instructions in the README though? I think the code blocks are in the wrong place and the wrapping and links are weird.

**Comment by Cam2337** [comment]
Thanks @benhannel! Oh interesting, it looked fine in MacDown. Will give it another look over and update!

**Comment by benhannel** [comment]
I was viewing it in the [Github preview,](https://github.com/Cam2337/snap-python/tree/master/docker) which I think is how most people will view it when they use it next year. They may use different flavors of markdown.

**Comment by roks** [comment]
Very nice, thank you! I accepted the request. Please update the README formatting as suggested by @benhannel and submit another request.

**Comment by Cam2337** [comment]
Thanks @roks, will do. I should have time to do this today.

**Pull request merged**
